using System.Collections.Generic;
using System.Data.Entity;
using ZooFeeding.Models;

namespace ZooFeeding.DAL
{
    public class ZooInitializer : DropCreateDatabaseIfModelChanges<ZooContext>
    {
        protected override void Seed(ZooContext context)
        {
            var animals = new List<Animal>
            {
                new Animal { AnimalName="African Bullfrog", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="African Crested Porcupine", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="African Lungfish", DryCatFood=false, Fish=true, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=true, Vegetables=false},
                new Animal { AnimalName="African Pygmy Hedgehog", DryCatFood=true, Fish=false, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="African Red-Billed Hornbill", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="African Rock Python", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=true, Vegetables=false},
                new Animal { AnimalName="African Slender-Snouted Crockodile", DryCatFood=false, Fish=true, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=true, Vegetables=false},
                new Animal { AnimalName="African Spurred Tortoise", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="African Wild Dog", DryCatFood=false, Fish=true, Fruit=false, Hay=false, Insects=false, Meat=true, MonkeyChow=true, Plants=false, Rodents=true, Vegetables=false},
                new Animal { AnimalName="Allen's Swamp Monkey", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=true, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="American Beavers", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=true, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="American Black Bear", DryCatFood=false, Fish=true, Fruit=true, Hay=false, Insects=false, Meat=true, MonkeyChow=false, Plants=false, Rodents=true, Vegetables=true},
                new Animal { AnimalName="Amur Leopard", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=true, MonkeyChow=false, Plants=false, Rodents=true, Vegetables=false},
                new Animal { AnimalName="Amur Tiger", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=true, MonkeyChow=false, Plants=false, Rodents=true, Vegetables=false},
                new Animal { AnimalName="Arrau Turtle", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=true, Vegetables=false},
                new Animal { AnimalName="Asian Elephant", DryCatFood=false, Fish=false, Fruit=true, Hay=true, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Austrailian Walking Stick", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Bald Eagle", DryCatFood=false, Fish=true, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=true, Vegetables=false},
                new Animal { AnimalName="Black Howler Monkey", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=true, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Black Rhinoceros", DryCatFood=false, Fish=false, Fruit=false, Hay=true, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Blue and Gold Macaw", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Blue-Streaked Lory", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Bobcat", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=true, MonkeyChow=false, Plants=false, Rodents=true, Vegetables=false},
                new Animal { AnimalName="Bontebok", DryCatFood=false, Fish=false, Fruit=false, Hay=true, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Bufflehead", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Bull Trout", DryCatFood=false, Fish=true, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Burmese Python", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=true, Vegetables=false},
                new Animal { AnimalName="California Condor", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=true, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Curacal", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=true, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Cattle Egret", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Cheetah", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=true, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Chimpanzee", DryCatFood=false, Fish=true, Fruit=false, Hay=false, Insects=true, Meat=true, MonkeyChow=true, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Cinnamon Teal", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Coho Salmon", DryCatFood=false, Fish=true, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Colombus Monkey", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=true, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Common Emperor Scorpion", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Cotton Top Tamarin", DryCatFood=true, Fish=false, Fruit=true, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Cougar", DryCatFood=true, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=true, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="De Brazza's Monkey", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=true, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Desert Tortoise", DryCatFood=false, Fish=false, Fruit=true, Hay=true, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Dwarf Caiman", DryCatFood=false, Fish=true, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=true, Vegetables=false},
                new Animal { AnimalName="Dwarf Mongoose", DryCatFood=true, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=true, Vegetables=true},
                new Animal { AnimalName="Egyptian Fruit Bat", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Emerald Starling", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Emerald Tree Boa", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=true, Vegetables=false},
                new Animal { AnimalName="Ferret", DryCatFood=true, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Giant African Millipede", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Giraffe", DryCatFood=false, Fish=false, Fruit=false, Hay=true, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Golden Eagle", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=true, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Golden Breasted Starling", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Grey Gull", DryCatFood=false, Fish=true, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Hadada Ibis", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Hamerkop", DryCatFood=false, Fish=true, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Harbor Seal", DryCatFood=false, Fish=true, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Harris Hawk", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=true, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Hippopotamus", DryCatFood=false, Fish=false, Fruit=false, Hay=true, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Hooded Vulture", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=true, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Hottentot Teal", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Humboldt Penguin", DryCatFood=false, Fish=true, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Inca tern", DryCatFood=false, Fish=true, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Indian Runner Duck", DryCatFood=true, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Kimkajoo", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Lesser Flamingo", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Lion", DryCatFood=true, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=true, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Madagascar Hissing Cockroach", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Malagen Sun Bear", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=true, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Mandrill", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=true, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Mexican Red-Kneed Tarantula", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Naked Mole Rat", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Nankin Chicken", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Nigerian Dwarf Goat", DryCatFood=true, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="North American River Otter", DryCatFood=true, Fish=true, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="North Sulawesi Barbirusa", DryCatFood=false, Fish=false, Fruit=true, Hay=true, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Northern Pintail", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Northern Shoveler", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Old World Rabbit", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Orangutan", DryCatFood=false, Fish=false, Fruit=true, Hay=true, Insects=false, Meat=false, MonkeyChow=true, Plants=true, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Oriole Warbler", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Ornate Monitor Lizard", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=true, Vegetables=false},
                new Animal { AnimalName="Pacu", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Philippine Sailfin Lizard", DryCatFood=false, Fish=true, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Polar Bear", DryCatFood=false, Fish=true, Fruit=false, Hay=false, Insects=false, Meat=true, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Pygmy Goat", DryCatFood=true, Fish=false, Fruit=false, Hay=true, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Pygora Goat", DryCatFood=true, Fish=false, Fruit=false, Hay=true, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Rainbow Trout", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Red-Bellied Piranha", DryCatFood=false, Fish=true, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Red-Crested Pochard", DryCatFood=false, Fish=false, Fruit=false, Hay=true, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Red Tailed Hawk", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=true, Vegetables=false},
                new Animal { AnimalName="Redhead", DryCatFood=false, Fish=false, Fruit=false, Hay=true, Insects=true, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Ringtail", DryCatFood=true, Fish=false, Fruit=true, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=true, Vegetables=false},
                new Animal { AnimalName="Rocky Mountain Goat", DryCatFood=true, Fish=false, Fruit=false, Hay=true, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Rodrigues Flying Fox", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Sacred Ibis", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Southern Ground Hornbill", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Southern Masked Weaver", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Southern Sea Otter", DryCatFood=true, Fish=true, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Speckled Mousebird", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Speke's Gazelle", DryCatFood=false, Fish=false, Fruit=false, Hay=true, Insects=false, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Straw-Colored Fruit Bat", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Turkey Vulture", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=true, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Veiled Chamelion", DryCatFood=false, Fish=false, Fruit=false, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Violet-Backed Starling", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=true, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Visayam Warty Pig", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="Western Painted Turtle", DryCatFood=false, Fish=false, Fruit=false, Hay=true, Insects=true, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="White Sturgeon", DryCatFood=false, Fish=true, Fruit=false, Hay=false, Insects=false, Meat=false, MonkeyChow=false, Plants=false, Rodents=false, Vegetables=false},
                new Animal { AnimalName="White Cheeked Gibbon", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=true, Meat=false, MonkeyChow=true, Plants=false, Rodents=false, Vegetables=true},
                new Animal { AnimalName="White-Faced Saki Monkey", DryCatFood=false, Fish=false, Fruit=true, Hay=false, Insects=true, Meat=false, MonkeyChow=true, Plants=true, Rodents=false, Vegetables=true},
                new Animal { AnimalName="White-Faced Whistling Duck", DryCatFood=false, Fish=false, Fruit=false, Hay=true, Insects=true, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false},
                new Animal { AnimalName="Wood Duck", DryCatFood=false, Fish=false, Fruit=false, Hay=true, Insects=true, Meat=false, MonkeyChow=false, Plants=true, Rodents=false, Vegetables=false}
            };
            animals.ForEach(a => context.Animals.Add(a));
            context.SaveChanges();
        }
    }
}